[project]
authors = [
  "Gui Castelao <guilherme@castelao.net>",
	"Paul Pinchuk <ppinchuk@nrel.gov>",
	]
channels = ["pytorch", "conda-forge", "anaconda", "main"]
description = "Migrating and benchmarking NREL data with Zarr, Xarray, & Dask."
name = "NREL-zarr-data"
platforms = ["osx-arm64", "linux-64", "linux-aarch64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11.0"
dask = ">=2024.8.1,<2026"
dask-labextension = ">=7.0.0,<8"
h5py = ">=3.8.0,<4"
jupyterlab = ">=4.3.4,<5"
ipython = ">=8.31.0,<9"
matplotlib = ">=3.9.1,<4"
netcdf4 = ">=1.6.3,<2"
nodejs = ">=18.15.0,<22.14"
nrel-rex = ">=0.2.84,<0.3"
scipy = ">=1.15.1,<2"
xarray = ">=2025.1.1,<2026"

[pypi-dependencies]
# For now, the required crc32c is not available in conda-forge for linux-arrch64
crc32c = ">=2.7.1, <3"
numcodecs = ">=0.15.0, <0.16"
zarr = ">=3.0"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[feature.dev.dependencies]
ruff = "*"
